sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_search:
    type: portal
    resource: "@SuluSearchBundle/Resources/config/routing_website.yml"

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing_website.yml"

# config/routes/sulu_community_website.yaml

sulu_community:
    type: portal
    resource: "@SuluCommunityBundle/Resources/config/routing_website.yaml"

when@dev:
    _portal_errors:
        resource: "@SuluWebsiteBundle/Resources/config/routing_error.yml"
        type: portal
